### PR TITLE
Merge packages into a single `voodoo` package

### PR DESCRIPTION
**Pull request by gpetiot**
Extracted from #62

Depends on #73

### CODE REVIEW

**Comment by TheLortex** [comment]
Hi, merging voodoo packages in a single package means that:
- voodoo-prep won't be installable for OCaml >= 4.03 & < 4.08
- any change in voodoo will require the CI to rebuild **everything**. This is very costly. When the packages are separated, we can easily figure out whether changes are impacting the prep step.

**Comment by jonludlam** [comment]
I'd like to remove support for <4.08 at some point in the near future, but not _yet_. In fact, we may want voodoo support for older OCamls to outlast odoc's (we'll just use an older odoc for older ocamls, potentially).

**Comment by sabine** [comment]
Sorry, I didn't give enough context on https://github.com/ocaml-doc/voodoo/pull/62. This is one of the changes of that PR that aren't feasible because the individual caching of build artifacts for the prep, do, and gen steps is valuable. :slightly_smiling_face:

**Comment by gpetiot** [comment]
Thanks for the explanation, let's close this PR then!

**Pull request closed without merging**
