### PR TITLE
List "other" doc files info (README, LICENSE, CHANGES) in status.json

### PR DESCRIPTION
**Pull request by gpetiot**
Suggested by @sabine

Based on #67 to simplify writing in the package.json file

### CODE REVIEW

**Comment by tmattio** [comment]
Is it something that can be added upstream in odoc? In general, let's try to keep the difference between odoc and voodoo to a minimum so that users of odoc can benefit from the improvements, and that we can consider moving to the dune driver one day.

**Comment by sabine** [comment]
Indeed, the question is whether README, LICENSE, CHANGELOG are part of the documentation that odoc deals with, or not.

The existing module tree in `package.json` is likely to be subsumed in the long run by a feature in odoc (e.g. odoc emitting a full package index from which we can extract a navigation like this).

**Comment by jonludlam** [comment]
odoc is almost entirely content agnostic - it only knows about mld files and cm{ti,t,i} files, and it doesn't care about the contents of them, so it's extremely unlikely it'll ever do anything special with these three files - especially because they aren't even mld files in most cases :-)

**Comment by sabine** [comment]
Makes sense to me. This is more of an OCaml.org-specific use case.

Though, maybe we want to put this info in status.json so that package.json can disappear in the long run when odoc provides a better functionality.

**Comment by gpetiot** [comment]
> Though, maybe we want to put this info in status.json

I've moved the info to status.json, let me know what you think

**Pull request merged**
