### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by tmattio**
Notable changes:

- Upgrade to odoc.2.2.0 to use the JSON output in place of the HTML one
- Upgrade to Omd.2.0.0~alpha3 which brings support for tables
- Add cram tests for different packages
- Move conversation of org to markdown to voodoo-do to generate the `.md.json` file during the gen stage

cc @sabine feel free to push changes to this branch, when we have a staging pipeline we can use it to test. I added cram tests so we should be able to iterate on this relatively safely.

### CODE REVIEW

**Comment by sabine** [comment]
Ok, so after finally understanding the pipeline a bit better, it is clear that we cannot apply this commit this without significant changes to the pipeline:

https://github.com/ocaml-doc/voodoo/pull/46/commits/1cd7818ace7f1f3d2416809786aa4c97381c357a [Merge packages into a single voodoo package](https://github.com/ocaml-doc/voodoo/pull/46/commits/1cd7818ace7f1f3d2416809786aa4c97381c357a)

The packages were intentionally separated because the three tools are applied as different tasks in the pipeline - in order to build only those steps where a cached build artifact is not available. Builds of the three tools (prep, do, gen) are cached based on the latest commit id within the respective folder.

Let's go through those commits one by one and see which are non-breaking changes (wrt both pipeline and ocaml.org), and deploy those.

**Comment by tmattio** [comment]
Thanks @sabine! I'm not sure I understand why having separated packages is a hard constraint. Couldn't the pipeline be modified to install the same package?

**Comment by sabine** [comment]
It could be modified. However, it caches the different build artifacts of the three tools with a key of the latest commit id - in order to prevent unnecessarily re-running the expensive voodoo-prep. This is probably again my ignorance showing wrt to opam and packages. :see_no_evil: If one package can expose three executables, then that is totally fine.

**Comment by jonludlam** [comment]
IIRC the motivation for having prep separate was that it's the only part of the process that is built at the same point as the package being documented, and therefore needs to have very minimal dependencies, and none that can't be built in all supported versions of the compiler.

**Pull request closed without merging**
